# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - tushar-joshi-acc-test-app

on:
  push:
    branches:
      - main

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tushar-joshi-acc-test-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6a5dd73887194f7588ad0b51771c69bb }}
        package: '${{ github.workspace }}/target/*.jar'
